Validations
mudasiri/mybloggerapp pull request #3
Opened 2023-06-09 21:40 UTC by mudasiri

In this PR, I did the following:

Added validations for models
Added units test for models

2023-06-09 23:17 UTC, franclobo requested changes
Hi @mudasiri, 

## ♻️ Required Changes ♻️

![istockphoto-1079018918-612x612](https://github.com/mudasiri/mybloggerapp/assets/58642949/2a4de405-d602-4caf-9300-74faadae8257)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Git flow ✔️ 
- Good validations ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 23:17 UTC, franclobo commented on spec/models/comment_spec.rb
> +    post.increment!(:comments_counter)
- [ ] Please 🙏🏽 correct the migrations to be able to create the correct tests for comments validations 👇🏽 

```bash
== 20230609141944 AddPostRefToComment: migrating ==============================
-- add_reference(:comments, :post_id, {:null=>false, :foreign_key=>true})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "post_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609141944_add_post_ref_to_comment.rb:5:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "post_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609141944_add_post_ref_to_comment.rb:5:in `change'

Caused by:
PG::UndefinedTable: ERROR:  relation "post_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609141944_add_post_ref_to_comment.rb:5:in `change'
Tasks: TOP => db:migrate
```
The correct migration should be:
```ruby
# frozen_string_literal: true

class AddPostRefToComment < ActiveRecord::Migration[7.0]
  def change
    add_reference :comments, :posts, null: false, foreign_key: true
  end
end
```

```bash
== 20230609142126 AddUserRefToComment: migrating ==============================
-- add_reference(:comments, :author_id, {:null=>false, :foreign_key=>true})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "author_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609142126_add_user_ref_to_comment.rb:5:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "author_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609142126_add_user_ref_to_comment.rb:5:in `change'

Caused by:
PG::UndefinedTable: ERROR:  relation "author_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609142126_add_user_ref_to_comment.rb:5:in `change'
Tasks: TOP => db:migrate
```

The correct migration should be:

```
# frozen_string_literal: true

class AddUserRefToComment < ActiveRecord::Migration[7.0]
  def change
    add_reference :comments, :author, column: :author_id, null: false, foreign_key: { to_table: :users }
  end
end
```

2023-06-09 23:17 UTC, franclobo commented on spec/models/like_spec.rb
> +    post.increment!(:likes_counter)
- [ ] Similar case with the comments, please 🙏🏽 correct the migrations to be able to create the correct validations tests.

```bash
== 20230609142239 AddUserRefToLike: migrating =================================
-- add_reference(:likes, :author_id, {:null=>false, :foreign_key=>true})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "author_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609142239_add_user_ref_to_like.rb:5:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "author_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609142239_add_user_ref_to_like.rb:5:in `change'

Caused by:
PG::UndefinedTable: ERROR:  relation "author_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609142239_add_user_ref_to_like.rb:5:in `change'
Tasks: TOP => db:migrate
```

```bash
== 20230609142450 AddPostRefToLike: migrating =================================
-- add_reference(:likes, :post_id, {:null=>false, :foreign_key=>true})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "post_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609142450_add_post_ref_to_like.rb:5:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "post_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609142450_add_post_ref_to_like.rb:5:in `change'

Caused by:
PG::UndefinedTable: ERROR:  relation "post_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609142450_add_post_ref_to_like.rb:5:in `change'
Tasks: TOP => db:migrate
```

2023-06-09 23:17 UTC, franclobo commented on spec/models/post_spec.rb
- [ ] Similar case with the comments and likes, please 🙏🏽 fix the migrations before creating the validations tests.

```bash
== 20230609142346 AddUserRefToPost: migrating =================================
-- add_reference(:posts, :author_id, {:null=>false, :foreign_key=>true})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "author_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609142346_add_user_ref_to_post.rb:5:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "author_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609142346_add_user_ref_to_post.rb:5:in `change'

Caused by:
PG::UndefinedTable: ERROR:  relation "author_ids" does not exist
/home/franclobo/microverse/mybloggerapp/db/migrate/20230609142346_add_user_ref_to_post.rb:5:in `change'
Tasks: TOP => db:migrate
```

2023-06-09 23:17 UTC, franclobo commented on app/models/user.rb
>    has_many :comments, foreign_key: 'author_id'
- [ ] To use the foreign_key: 'author_id' we should define the column author_id in the corresponding migration, like this 👇🏽 

```ruby
# frozen_string_literal: true

class AddUserRefToComment < ActiveRecord::Migration[7.0]
  def change
    add_reference :comments, :author, column: :author_id, null: false, foreign_key: { to_table: :users }
  end
end
```

2023-06-09 23:17 UTC, franclobo commented on app/models/post.rb
> +  validates :comments_counter, numericality: { only_inter: true, greater_than_or_equal_to: 0 }
- [ ] To use comment**s**_counter we should define the column in the corresponding migration 👇🏽 

```ruby
# frozen_string_literal: true

class CreatePost < ActiveRecord::Migration[7.0]
  def change
    create_table :posts do |t|
      t.string :title
      t.string :text
      t.integer :comments_counter
      t.integer :likes_counter

      t.timestamps
    end
  end
end
```

2023-06-10 02:02 UTC, mudasiri commented on spec/models/comment_spec.rb
> +    post.increment!(:comments_counter)
Updated the names

2023-06-10 02:48 UTC, andersonlebon requested changes
## Hi @mudasiri 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 02:48 UTC, andersonlebon commented on db/migrate/20230609142126_add_user_ref_to_comment.rb
> +    add_reference :comments, :author, column: :author_id, null: false, foreign_key: { to_table: :users }
<img width="976" alt="image" src="https://github.com/mudasiri/mybloggerapp/assets/65068771/ba104beb-1db6-4700-be08-15e03320f2fc">

- [ ] Kindly make sure solve all your migration errors the same way you did in the above. check in all the migration that are referencing the user model, the should specify the table. like this

for the post table
```rb
add_reference :posts, :author, column: :author_id, null: false, foreign_key: { to_table: :users }
```

for the comment  table
```rb
add_reference :comments, :author, column: :author_id, null: false, foreign_key: { to_table: :users }
```
for the like table
```rb
add_reference :likes, :author, column: :author_id, null: false, foreign_key: { to_table: :users }
```

2023-06-10 11:45 UTC, addod19 requested changes
Hi @mudasiri , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [ ] Nice job addressing some of the comments from the previous reviews :100: 


 ## Required Changes ♻️
_Check the comments under the review._
- [ ] Here is a [link](https://guides.rubyonrails.org/active_record_migrations.html) to help us understand more about active record migrations

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 11:45 UTC, addod19 commented on db/migrate/20230609140544_create_post.rb
> +      add_reference :posts, :author, column: :author_id, null: false, foreign_key: { to_table: :users }
- [ ] Kindly move this piece of code outside the `create_table :posts` block, let the code be between `line12 & line13`
![Screenshot from 2023-06-10 11-38-29](https://github.com/mudasiri/mybloggerapp/assets/46388113/d5f03e15-eb63-4491-b04d-edef0909adbc)

2023-06-10 11:45 UTC, addod19 commented on db/migrate/20230609140917_create_comment.rb
> +      add_reference :comments, :author, column: :author_id, null: false, foreign_key: { to_table: :users }
- [ ] Kindly move this piece of code outside the `create_table :comments` block, let the code be between `line12 & line13`
This is how our code should like like but not exactly the same
```
create_table :comments do |t|
      t.text :text
      t.integer :author_id
      t.integer :post_id

      t.timestamps
end
add_foreign_key :comments, :users, column: :author_id
add_foreign_key :comments, :posts, column: :post_id
add_index :comments, :author_id
add_index :comments, :post_id
```

2023-06-10 13:08 UTC, mudasiri commented
@addod19  please I have exhausted all my reviews, so kindly re-check my update and approve it here so I can submit it.

2023-06-10 14:25 UTC, franclobo approved these changes
Hi @mudasiri, 

# STATUS: APPROVED 😃 

![git-merge](https://github.com/mudasiri/mybloggerapp/assets/58642949/df5b6fe3-52f2-4bd3-b921-4bde4d2982a2)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Correct Git flow ✔️ 
- Descriptive PR ✔️ 
- Correct migrations ✔️ 
- All tests passed 💯 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 14:33 UTC, merged