Add device
mudasiri/mybloggerapp pull request #9
Opened 2023-06-23 17:27 UTC by mudasiri

In this PR, I added the following functionalities:

Can register a new user.
User logs in with a combination of email and password.
Hashed password should be stored in the database.
Ask for confirmation of email.
Can reset password.

2023-06-23 18:17 UTC, TadesseDev requested changes
### Hi Team

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)




## Highlights
 - [x] Good job overall following the template design ✅
 - [x]  Correct GitFlow  ✅
 - [x]  Good commit history  ✅
 - [x]  Good PR title/description  ✅
 - [x]  All linters passed  ✅
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 18:17 UTC, TadesseDev commented on app/models/user.rb
>    has_many :comments, foreign_key: 'author_id'
- [ ] Dear Team, Your functional implementations great, But I notice your layout is a bit off compared with the provided wireframe. Please keep inmind the views in devise for the registration and login is expected to be modified. 

### Your design 
![image](https://github.com/mudasiri/mybloggerapp/assets/69077061/59749c42-d229-4954-ac63-2b4e156e2118)

### The wireframe
![blog_login](https://github.com/mudasiri/mybloggerapp/assets/69077061/873bb0b5-540d-4d6d-9331-3033ee58ef60)

2023-06-23 22:25 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi team 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media1.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Good commit history
✔️ Implement authentication with Devise 📌 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] Please use imperative tense in your commit messages as that is the recommended way to write commit messages. So instead of "added devise", you can write "Add devise". Please let your next commit messages reflect this 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 22:25 UTC, codepantha commented on app/views/devise/sessions/new.html.erb
> +</div>
- [ ] Just as the previous reviewer suggested, please let's make the login and register pages follow the wireframe guidelines:
1. Ensure that the login and register forms take up a considerable portion of the screen as shown in the wireframe.
2. Also ensure that the width of the  login and sign up buttons match that of the input fields.
### Wireframe Guidelines
![image](https://github.com/mudasiri/mybloggerapp/assets/46839548/7710162e-9f98-4f9a-b112-bf6049f7bd72)
### Your Design
![image](https://github.com/mudasiri/mybloggerapp/assets/46839548/1daf9291-680e-44ca-b7e1-1059bc0ca081)

2023-06-23 22:34 UTC, merged

2023-06-24 13:20 UTC, franclobo reviewed
Hi @mudasiri, 

# Invalid Code Review Request

![descarga](https://github.com/mudasiri/mybloggerapp/assets/58642949/97856c71-3581-4f26-8299-0c9f16b4523a)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is merged without approval.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._